# Generated by Django 6.0.1 on 2026-02-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
