# Generated by Django 6.0 on 2026-02-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
